Repository PausedMagician/Carp, pull requests merged in 2025-10, with the labels that each got.

#24 Mock data
  .gitignore
  .vscode/settings.json
  App/App.tsx
  App/app.json
  App/app/Home.tsx
  App/app/Screens.ts
  App/app/login/Login.tsx
  App/app/profile/Profile.tsx
  App/app/profile/ProfileStyles.ts
  App/app/settings/SettingsScreen.tsx
  App/app/settings/SettingsStyles.ts
  App/app/vehicles/VehiclesScreen.tsx
  App/assets/adaptive-icon.png
  App/assets/favicon.png
  App/assets/fish.png
  App/assets/icon.png
  App/assets/images/cars/1.png
  App/assets/images/cars/2.png
  App/assets/splash-icon.png
  App/backend/Server.ts
  App/components/CarListItem.tsx
  App/constants/Stylings.ts
  App/contexts/AuthContext.tsx
  App/hooks/UseAuth.tsx
  App/index.ts
  App/package-lock.json
  App/package.json
  App/tsconfig.json
  App/types/openapi.d.ts
  backend/.gitignore
  backend/AppDataSource.ts
  backend/Data/Bookings.json
  backend/Data/Logs.json
  backend/Data/Maintenances.json
  backend/Data/MockData.ts
  backend/Data/Users.json
  backend/Data/Vehicles.json
  backend/Server.ts
  backend/Server_old.ts
  backend/controllers/BookingController.ts
  backend/controllers/CompanyController.ts
  backend/controllers/EmployeeController.ts
  backend/controllers/LogController.ts
  backend/controllers/MaintenanceController.ts
  backend/controllers/VehicleController.ts
  backend/entities/Booking.ts
  backend/entities/Company.ts
  backend/entities/Employee.ts
  backend/entities/LogEntry.ts
  backend/entities/Maintenance.ts
  backend/entities/PersonalDetails.ts
  backend/entities/Vehicle.ts
  backend/entities/VehicleRegistration.ts
  backend/entities/VehicleSpec.ts
  backend/entities/VehicleTransmission.ts
  backend/package-lock.json
  backend/package.json
  backend/tsconfig.json
  types/Car.ts
Labels: enhancement

#25 Feature/carousel
  App/app/Home.tsx
  App/components/ActiveBooking.tsx
  App/components/CarCarousel.tsx
  App/components/CarCarouselItem.tsx
  App/package-lock.json
  App/package.json
Labels: enhancement

#27 initial and final commit for images
  App/components/CarCarouselItem.tsx
  App/types/openapi.d.ts
  backend/Server.ts
  backend/assets/images/vehicles/1.png
  backend/assets/images/vehicles/2.png
  backend/assets/images/vehicles/placeholder.png
  backend/controllers/ImageController.ts
Labels: enhancement

#28 Login implement
  App/types/openapi.d.ts
  backend/Server.ts
  backend/controllers/EmployeeController.ts
Labels: enhancement

#34 Fixed
  App/app/vehicles/VehiclesScreen.tsx
  App/components/CarListItem.tsx
Labels: bug

#35 Actually fixed
  App/app/HomeScreen.tsx
  App/app/home/HomeScreen.tsx
Labels: bug, duplicate

#37 Theme styles supports dark mode
  App/App.tsx
  App/AppStyles.ts
  App/app/admin/AdminScreen.tsx
  App/app/admin/AdminStyles.ts
  App/app/booking/BookingDateScreen.tsx
  App/app/booking/BookingStyles.ts
  App/app/home/HomeScreen.tsx
  App/app/profile/ProfileScreen.tsx
  App/app/profile/ProfileStyles.ts
  App/app/settings/SettingsScreen.tsx
  App/app/settings/SettingsStyles.ts
  App/components/ActiveBooking.tsx
  App/components/CarCarousel.tsx
  App/components/CarCarouselItem.tsx
  App/components/CarListItem.tsx
  App/constants/Stylings.ts
  App/constants/theme.ts
  App/hooks/useThemedStyles.ts
Labels: bug, enhancement

#53 Fixing "Text strings must be rendered within a <Text> component"
  App/components/ActiveBooking.tsx
Labels: bug

#55 Fixing selected Calendar dates not persisting
  App/app/booking/BookingDateScreen.tsx
Labels: bug

#56 Refactoring of Booking
  App/App.tsx
  App/AppStyles.ts
  App/app/booking/BookingConfirmationScreen.tsx
  App/app/booking/BookingDateScreen.tsx
  App/app/booking/BookingStyles.ts
  App/app/booking/BookingSuccessScreen.tsx
  App/app/home/HomeScreen.tsx
  App/app/home/HomeStyles.ts
  App/components/CarCarousel.tsx
  App/components/booking/BookingDetailRow.tsx
  App/components/booking/BottomActionBar.tsx
  App/components/booking/DateRangeDisplay.tsx
  App/components/booking/DestinationInput.tsx
  App/components/booking/ErrorCard.tsx
  App/components/booking/PurposeInput.tsx
  App/components/booking/UserInfoCard.tsx
  App/components/booking/VehicleCard.tsx
  App/constants/booking.ts
  App/constants/icons.ts
  App/constants/theme.ts
  App/hooks/useVehicleImage.ts
  App/navigation/HomeStack.tsx
  App/utils/bookingUtils.ts
  App/utils/errorHandling.ts
Labels: enhancement
